# Generated by Django 2.1 on 2020-01-09 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_articlepost_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlepost',
            options={'ordering': ('-created',)},
        ),
    ]
